### ISSUE TITLE
Create Google Doc with deq14 descriptives

### ISSUE THREAD

**Issue by hzadeh17** [ui-libraries/flint#15]
Include estimated number of emails based on timestamps and From:/On...'s; number and list of different people in email headers; ratio of From: to On... headers; ...

@Louise-Seamster, anything else?

**Comment by Louise-Seamster** [comment]
this is enough to start with! I'm sure we'll think of more when we see the first bits.

**Comment by hzadeh17** [comment]
will keep updating as new things emerge, but [here](https://docs.google.com/document/d/1KWrOs1ZCFjtbSAAPglCQZY7etvmYkl4GtvOUSRpgcgg/edit) is what I've got so far!

**Comment by Louise-Seamster** [comment]
thanks, this is helpful! I made a few comments.
