### ISSUE TITLE
Find a way to discern the reciever in emails with "On...wrote:" headers

### ISSUE THREAD

**Issue by hzadeh17** [ui-libraries/flint#16]
Problem: "On...wrote:" headers do not explicitly state the receiver of the email, but it can be ascertained using context clues, such as the body of the email (e.g. Hi Dayne, bla bla bla) or the sender of the email before it in a thread. Try to find a way to automate this process in python.

**Comment by Louise-Seamster** [comment]
@hzadeh17 should I close this issue?

**Comment by hzadeh17** [comment]
@Louise-Seamster I think so? this is still a problem, but I'm thinking that this might be something that will have to be done by hand as one of the tasks in the app, esp because there aren't a huge number of On's anyway. right now in the database On headers have "NOREC" in the To: and Cc: receiver fields.

**Comment by Louise-Seamster** [comment]
ok I'll start a list of tasks like this
