### ISSUE TITLE
Data cleaning and new data formats needed

### ISSUE THREAD

**Issue by akrinaldi** [ui-libraries/flint#24]
For the calendar I made in R, I found that the date format that gives R the least amount of hassle is YEAR-MONTH-DAY. That said, our dates are formatted in a variety of different ways. I've been using datetime and strptime to change some of the dates around, to varying degrees of success. I have it where we get the dates (just the dates, no TOD data, as that confuses the function I'm using to make the calendar) and have them as a list of strings. Then, I can use the following to successfully reformat them:

`strings = ['Wednesday October 28 2015', 'Monday October 26 2015']`
```
for string in strings:
    object2 = datetime.strptime(string, '%A %B %d %Y')
    print(datetime.strftime(object2,'%Y-%m-%d'))
```
That prints the result

`2015-10-28`
`2015-10-26`

That's perfect! But, it only works when I have a list of the same KIND of date. I haven't gotten a working loop for a list that includes multiple date types. Anyone know how to pull this loop off?

**Comment by hzadeh17** [comment]
We have about 99% of the timestamps in unix format, will that work?

**Comment by akrinaldi** [comment]
The unix stamps work so perfectly it's ridiculous.
