### ISSUE TITLE
Creating filtered datasets

### ISSUE THREAD

**Issue by akrinaldi** [ui-libraries/flint#25]
So, from what I can tell, we need four types of datasets for the calendars and tables. 
 
   1. The list of unix timestamps with duplicates (no other variables)
   2. The list of unix timestamps without duplicates (no other variables)
   3. All DEQ data for the tables, with unix timestamps and senders/receivers
   4. Emails from all DEQs for each unique year 

I have the code to create the lists of dates translated from unix to a readable format for R, so the first two lists will allow me to make new heat maps which we can compare to see where most of our duplicates are. The third list will give me the master table, while the last list set will be for tables to accompany the calendars. 

Let me know what is needed from me to help get these lists together. Also, I can post my converted timestamp sets as raw data on GitHub so we can use them outside of visualizations if necessary.

**Comment by hzadeh17** [comment]
these files should solve 1 and 2.

[UTSyesdup.txt](https://github.com/ui-libraries/flint/files/4789510/UTSyesdup.txt) -- full list of UTS with duplicates
[UTSnodup.txt](https://github.com/ui-libraries/flint/files/4789514/UTSnodup.txt) -- full list of rounded UTS, no duplicates (dups sniffed out using rounding and sender-matching method)
[UTSnodup_count.txt](https://github.com/ui-libraries/flint/files/4789511/UTSnodup_count.txt) -- that same list of UTS no dups, but in a tuple with the frequency

a few things to note:
- the latter two files are only based on about 95% of the data (see [this issue](https://github.com/ui-libraries/flint/issues/26) for working on this problem
- the lists are sorted, so you will definitely see on either tail end some rogue timestamps in the future or distant past, so unless deq and kwa started conspiring in the 60s, those are errors I will have to look into

**Comment by hzadeh17** [comment]
As for 3, I have this output generated, but I don't know if it is in the format you'd like it to be in. Let me know!
[UTS_SND_DEQ.txt](https://github.com/ui-libraries/flint/files/4789587/UTS_SND_DEQ.txt)

**Comment by akrinaldi** [comment]
If you could give me that last list as a csv file, that would be super.

**Comment by hzadeh17** [comment]
yes! [Archive.zip](https://github.com/ui-libraries/flint/files/4801779/Archive.zip)
in this folder, uts_snd_deq.csv includes the NOTIMESTAMP placeholders and uts_snd_deq_noNOTS.csv does not include those. i'm guessing you'll want to use the latter file for the calendar because the NOTIMESTAMP placeholders will be useless on the calendar, but should probably be included in the table.
