### ISSUE TITLE
total number of DEQ emails

### ISSUE THREAD

**Issue by Louise-Seamster** [ui-libraries/flint#31]
I'm thinking through the basic statistics that would be very useful to have in a week or so for grantwriting.
7629 emails have no match, but that's not the same as saying there's only 7629 emails in the dataset.  perhaps as a step in this next process of choosing a "canonical" email from matching timestamps, can you tell me the overall number of emails, which involves adding to this "unique" number one iteration of each non-unique email? ie if an email has three Type-B duplicates, it returns a 1 so the email is counted?

**Comment by hzadeh17** [comment]
so you mean the overall number of emails, including duplicates? or is this something different?

**Comment by Louise-Seamster** [comment]
Yes, but not the number you have already computed, not the 24,000-whatever number. It would be the number you get if you add all the unique emails and one copy of each duplicate email. Does that make sense?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Louise-Seamster** [comment]
I also realized this would affect the results in @akrinaldi's heatmaps.
