### ISSUE TITLE
evaluate email breaks in data sample

### ISSUE THREAD

**Issue by Louise-Seamster** [ui-libraries/flint#5]
using the list created in issue https://github.com/ui-libraries/flint/issues/4, read through approx ten emails in the line by line output (divide up this task between Elliot and Hannah) to document what's coming before and after (how many line breaks, what's the first and last line look like, etc). 
This is a place to play around with creating python scripts to do the same, but it might help to look first with human eyes at what you see, or to intermittently switch between the two modes. Please document all your experiments and explain your steps (and note here where this work is, ideally pushed onto Github). It also appears you can link pull requests into issues, so you could do that when you're ready to add it on here? 
After you each have a summary of the subsection of emails you looked at, Elliot, Hannah and Dr. Seamster will discuss fundings and decide what columns to put in a .csv file documenting email breaks more systematically.
and you can also comment on here to divvy up tasks.

**Comment by hzadeh17** [comment]
Hello! So I went through the subset of deq14s created from [this script](https://github.com/ui-libraries/flint/blob/master/gettingdeq14filenames.ipynb) and took some notes on what I found in the Drive [here](https://docs.google.com/document/d/19ihfSRsfUZZIMfcalQZv_79yVXRUp6vUhaz2mALmHeg/edit).
Overall, I didn't end up finding out a ton about what signifies email starts that we don't already know. **From:** and **On:** are common starters. Additionally, at least for emails contained within bookmarks, the bookmark will often start with 3 new line spaces and then **From:**. I wasn't able to find any consistent patterns as to the end of emails. 

Also, I don't know if this is important, but I am curious about the inconsistencies in double- and single-spacing in the raw text. See document.
